### ISSUE TITLE
HLS stream: If the stream doesn't contain audio, it shouldn't declare a track.

### ISSUE THREAD

**Issue by liutingdu** [evercam/evercam-media#148] opened 2015-11-24 17:46 UTC
This is related to playing HLS stream in ExoPlayer on Android

https://github.com/google/ExoPlayer/issues/970

**Comment by marcoherbst** [comment] 2016-01-22 09:07
@mosic @liutingdu @GNUDimarik  ... I've just posted a bounty on the NGINX bug, FYI.:

https://www.bountysource.com/issues/28646289-how-to-disable-audio-track-for-hls

:)

M

**Comment by GNUDimarik** [comment] 2016-01-22 09:14
You are the Man :)
22 янв. 2016 г. 12:07 пользователь "Marco Herbst" <notifications@github.com>
написал:

**Comment by mosic** [comment] 2016-01-22 10:31
Nice :+1:

**Comment by mosic** [comment] 2016-02-02 22:07
@marcoherbst I've solved partially by adding a silent track in ffmpeg, but it would be nice if nginx-rtmp worked as intended. Should we close this issue or?

**Comment by marcoherbst** [comment] 2016-02-02 22:08
Yes. We've enough other issues to worry about :)

**Closed by marcoherbst** 2016-02-02 22:08 UTC
Labels: bug
